---
title: "Week 12: Causal Forests for Heterogeneous Treatment Effects"
subtitle: "*DSAN 5650: Causal Inference for Computational Social Science*<br><span class='subsubtitle'>Summer 2026, Georgetown University</span>"
author: "Jeff Jacobs"
institute: "[`jj1088@georgetown.edu`](mailto:jj1088@georgetown.edu)"
bibliography: "../_DSAN5650.bib"
date: 2026-08-05
date-format: full
lecnum: 12
categories:
  - "Class Sessions"
tbl-cap-location: bottom
crossref:
  fig-title: "Fig"
  title-delim: ". "
format:
  revealjs:
    df-print: kable
    footer: "DSAN 5650 Week 12: {{< var w12.footer >}}"
    output-file: "slides.html"
    html-math-method: mathjax
    scrollable: true
    link-external-icon: true
    link-external-newwindow: true
    echo: true
    code-fold: true
    theme: [default, "../dsan-globals/jjquarto.scss"]
    include-in-header:
      text: "<link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css'><link rel='stylesheet' type='text/css' href='https://cdn.jsdelivr.net/gh/dreampulse/computer-modern-web-font@master/fonts.css'>"
    slide-number: true
    simplemenu:
      flat: true
      barhtml:
        header: "<div class='menubar'><span style='position: absolute; left: 8; padding-left: 8px;'><a href='./index.html'>&larr; Return to Notes</a></span><ul class='menu'></ul></div>"
      scale: 0.5
    revealjs-plugins:
      - simplemenu
  html:
    df-print: kable
    output-file: "index.html"
    html-math-method: mathjax
    link-external-icon: true
    link-external-newwindow: true
    echo: true
    code-fold: true
    include-in-header:
      text: "<link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css'><link rel='stylesheet' type='text/css' href='https://cdn.jsdelivr.net/gh/dreampulse/computer-modern-web-font@master/fonts.css'>"
---

::: {.content-visible unless-format="revealjs"}

<center>
<a class="h2" href="./slides.html" target="_blank">Open slides in new window &rarr;</a>
</center>

:::

# Schedule {.smaller .crunch-title .crunch-callout .code-90 data-stack-name="Schedule"}

Today's Planned Schedule:

| | Start | End | Topic |
|:- |:- |:- |:- |
| **Lecture** | 6:30pm | 6:45pm | [Final Projects &rarr;](#final-project--end-of-term-things) |
| | 6:45pm | 7:10pm | [Included Variable Bias &rarr;](#does-aging-cause-sadness)
| | 7:10pm | 8:00pm | [Heterogeneous Treatment Effects &rarr;](#heterogeneous-treatment-effects) |
| **Break!** | 8:00pm | 8:10pm | |
| | 8:10pm | 9:00pm | [Causal Forests &rarr;](#causal-forests) |

: {tbl-colwidths="[12,12,12,64]"}

{{< include ../dsan-globals/_globals-tex.qmd >}}

## Final Project / End of Term Things

* **Midterm** grading will be done TONIGHT
* **Submit button** for HW3 / HW4 TONIGHT

## Sensitivity Analysis {.smaller .crunch-title}

* So you've got an estimate of a causal effect! What now? Two possible next steps...
* <i class='bi bi-1-circle'></i> **Sensitivity Analysis**: Check **robustness** of your results
  * Modeling choices &rarr; **one point** in param space (*garden of forking paths*)
  * If results "truly" hold, shouldn't disappear with small changes in parameters/choices
  * *Last week*: Can re-estimate with **informative** &rarr; **weak** &rarr; **skeptical** priors
  * *This week*: Simulate **how "strong"** omissions would have to be to **"ruin" finding**
* <i class='bi bi-2-circle'></i> **Heterogeneous Treatment Effects**: How does the effect **vary** btwn subgroups?
  * Example today: PROGRESA (Cash transfer poverty-alleviation program in Mexico)
  * Program has an **overall** causal effect, but also a **greater** causal effect on **indigenous** households, relative to non-indigenous
  * How can we find group-specific effects? **Causal forests!**

## References

::: {#refs}
:::
