
# Hard Mode: When Conditioning Isn't an Option / Can't Fix Things {.title-09 .crunch-title .text-90 data-name="Instrumental Variables"}

* Approaches we've discussed thus far depend on the ability to **adjust for** (e.g., by conditioning-on and/or purposefully-not-conditioning-on) **confounders themselves** (e.g., in regression), or on **propensity scores**
* Enter **Instrumental Variables!** (this week), **Specification of Mechanisms / Front-Door Pathways** (next week)
* $\leadsto$ Find **"natural experiments"**, randomizations or pseudo-randomizations in society that allow us to replicate the "holy grail" of random assignment

::: {.notes}

I... always ask economists why it isn't explained like this, and they always say "it's more complicated than that", and then they explain the complications and I think I understand them but still think that this is a good way to describe the gist!

:::

---

:::: {.columns}
::: {.column width="50%"}

<center>

**Independent** Variable / Treatment $D$

</center>

* What happens when...
  * [Someone gets a degree/internship]
  * [There are casualties in a conflict]
* Start with independent var $\Rightarrow$ *"What are the effects of this cause?"*

:::
::: {.column width="50%"}

<center>

**Dependent** Variable / Outcome $Y$

</center>

* *"I wonder what **explains this?**"*
  * [Differences in earnings]
  * [Probability of news story]
* Start with dependent var $\Rightarrow$ *"What are the causes of this effect?"*

:::
::::

---

$$
\begin{align*}
\hat \tau_{AIPW} &= \frac{1}{n} \sum_{i=1}^{n} \left( \text{RegEst}(X_i) + \text{PropensityAdj}(X_i, Y_i) \right) \\
\text{RegEst}(X_i) &= \hat \mu^{(1)}(X_i) - \hat \mu^{(0)}(X_i) \\
\text{PropensityAdj}(X_i, Y_i) &= \frac{D_i}{\hat{\mathtt{e}}(X_i)} \left( Y_i - \hat \mu^{(1)}(X_i) \right) - \frac{(1-D_i) }{1-\hat{\mathtt{e}}(X_i)} \left( Y_i - \hat \mu^{(0)}(X_i) \right)
\end{align*}
$$

* $\mu^{(d)}(x)$ is the **response function**, i.e. the expected value of the outcome, conditional on observable characteristics $x$ and treatment status $d$
* $\hat{\texttt{e}}(X)$ is the **estimated propensity score**.

$$
\begin{align*}
\mu^{(d)}(x) &= \mathbb E \left[ Y_i \ \big | \ X_i = x, D_i = d \right] \\
\mathtt{e}(x) &= \mathbb E \left[ D_i = 1 \ \big | \ X_i = x \right]
\end{align*}
$$